project:
  type: website
  output-dir: docs

website:
  title: "Natalia da Silva"
  page-navigation: true
  site-url: "https://natydasilva.com/"
  google-analytics: "G-2J79YYG9CZ"
  page-footer:
    left: "Website made with [Quarto](https://quarto.org/), by Natalia da Silva. License: [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/)."
  navbar:
   right:
      - href: index.qmd
        text: Home
      # - href: packages.qmd
      #   text: Software
      - href: publications.qmd
        text: Publications
      # - href: projects.qmd
      #   text: Projects
      - href: talks.qmd
        text: Talks
      - href: teaching.qmd
        text: Teaching
      - href: rpkg.qmd
        text: R_proy

   
lang: en
format:
  html:
    theme:
      light: pulse
      dark: [pulse, theme-dark.scss]
    css: styles.css
    toc: true
    # backgroundcolor: "#7B7C74"
editor: visual

execute:
  freeze: true

