project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Natalia da silva"
  site-url: "https://natydasilva.com/"
  google-analytics: "G-2J79YYG9CZ"
  page-footer:
    left: "Website made with [Quarto](https://quarto.org/), by Natalia da Silva. License: [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/)."
    # right:
    #   - icon: github
    #     href: https://github.com/natydasilva
    #   - icon: linkedin
    #     href: https://www.linkedin.com/in/natalia-da-silva-770700a1/
    #   - icon: envelope
    #     href: natalia.dasilva@fcea.edu.uy
      
  navbar:
    right:
      - text: About
        href: about.qmd
      - href: research.qmd
      - href: teaching.qmd
      - href: Blogs.qmd
      
      - icon: github
        href: https://github.com/natydasilva
      - icon: linkedin
        href: https://www.linkedin.com/in/natalia-da-silva-770700a1/

lang: pt

format:
  html:
    smooth-scroll: true
    theme:
      - pulse
      - custom.scss
    link-external-icon: false
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/www\.beamilz\.com\/**'
    citations-hover: true
    footnotes-hover: true
    toc: true
    code-link: true

editor: visual

comments:
  giscus:
    repo: natydasilva/natydasilva

execute:
  freeze: true