---
title: "Research"
editor: visual
page-layout: full
title-block-banner: true
---

::: {#hero-heading}

## Papers

- Wrobel, J., Hector, E. C., Crawford, L., McGowan, L. D., da Silva, N., Goldsmith, J., … Wolfson, J. (2024). Partnering With Authors to Enhance Reproducibility at JASA. *Journal of the American Statistical Association*, 119(546), 795–797. [https://doi.org/10.1080/01621459.2024.2340557](https://doi.org/10.1080/01621459.2024.2340557)

- da Silva, N., Cook, D. & Lee, EK. Interactive graphics for visually diagnosing forest classifiers in R. *Comput Stat* (2023). [https://doi.org/10.1007/s00180-023-01323-x](https://doi.org/10.1007/s00180-023-01323-x)

- da Silva, N. (2023). Intersection between environmental data science and the R community in Latin America. *Environmetrics*, 34(2), e2731.[ https://doi.org/10.1002/env.2731]( https://doi.org/10.1002/env.2731)

- Lee, S., Cook, D., da Silva, N., Laa, U., Spyrison, N., Wang, E., & Zhang, H. S. (2022). The state‐of‐the‐art on tours for dynamic visualization of high‐dimensional data. Wiley Interdisciplinary Reviews: *Computational Statistics*, 14(4), e1573.[https://doi.org/10.1002/wics.1573](https://doi.org/10.1002/wics.1573)

- da Silva, N., Cook, D., & Lee, E. K. (2021). A Projection Pursuit Forest Algorithm for Supervised Classification. *Journal of Computational and Graphical Statistics*, 30(4), 1168–1180. [https://doi.org/10.1080/10618600.2020.1870480](https://doi.org/10.1080/10618600.2020.1870480)

- da Silva, N., Alvarez-Castro, I. Clicks and cliques: exploring the soul of the community. *Comput Stat* 34, 1537–1563 (2019). [https://doi.org/10.1007/s00180-019-00881-3](https://doi.org/10.1007/s00180-019-00881-3)


- O’Connor, A. M., Yuan, C., Cullen, J. N., Coetzee, J. F., Da Silva, N., & Wang, C. (2016). A mixed treatment meta-analysis of antibiotic treatment options for bovine respiratory disease–an update. *Preventive veterinary medicine*, 132, 130-139.[https://doi.org/10.1016/j.prevetmed.2016.07.003](https://doi.org/10.1016/j.prevetmed.2016.07.003)

- O'Connor AM, Yuan C, Cullen JN, Coetzee JF, da Silva N, Wang C. A mixed treatment meta-analysis of antibiotic treatment options for bovine respiratory disease - An update. *Prev Vet Med*. 2016 Sep 15;132:130-139. doi: [https://doi.org/10.1016/j.prevetmed.2016.07.003](https://doi.org/10.1016/j.prevetmed.2016.07.003). Epub 2016 Aug 31. PMID: 27612392.


- Cullen JN, Yuan C, Totton S, Dzikamunhenga R, Coetzee JF, da Silva N, Wang C, O'Connor AM. A systematic review and meta-analysis of the antibiotic treatment for infectious bovine keratoconjunctivitis: an update. *Anim Health Res Rev*. 2016 Jun;17(1):60-75. [https://doi.org/10.1017/S1466252316000050](https://doi.org/10.1017/S1466252316000050). *PMID*: 27427193.

- Woods BJ, Millman ST, da Silva N, Dewell RD, Parsons RL, Wang C, O'Connor AM. Pain and sickness behavior associated with corneal lesions in dairy calves. *F1000Res*. 2015 Aug 11;4:546. [https://doi.org/10.12688/f1000research.6649.1](https://doi.org/10.12688/f1000research.6649.1). PMID: 26949517; PMCID: PMC4758373.

- da Silva N, Carriquiry A, O'Neill K, Opriessnig T, O'Connor AM. Mixed treatment comparison meta-analysis of porcine circovirus type 2 (PCV2) vaccines used in piglets. *Prev Vet Med*. 2014 Dec 1;117(3-4):413-24. doi: [https://doi.org/10.1016/j.prevetmed.2014.10.006](https://doi.org/10.1016/j.prevetmed.2014.10.006). Epub 2014 Oct 31. PMID: 25457512.

- O'Connor AM, Coetzee JF, da Silva N, Wang C. A mixed treatment comparison meta-analysis of antibiotic treatments for bovine respiratory disease. *Prev Vet Med*. 2013 Jun 1;110(2):77-87. doi: [https://doi.org/10.1016/j.prevetmed.2012.11.025](https://doi.org/10.1016/j.prevetmed.2012.11.025). Epub 2012 Dec 28. PMID: 23276402.


<!-- \item[2012]Forteza, A.,  Alvarez, I., da Silva, N.,  Rossi, I. ``Incentivos y patrones de retiro en Uruguay.'' -->
<!-- \textit{Estudios Economicos 2012, 27 (2)} -->

<!-- \item[2010] Forteza, A.,  Alvarez, I., da Silva, N.,  Rossi, I ``Qu\'e Incentivos al Retiro Genera la Seguridad Social? El Caso Uruguayo.'' \\ -->
<!-- \textit{Latin American Journal of Economics, Instituto de Econom\'ia. Pontificia Universidad Cat\'olica de Chile., vol. 47(136), pages 217-247}.  -->

<!-- \item[2009] Forteza, A.,  Alvarez, I., da Silva, N.,  Rossi, I.``El retiro de los trabajadores uruguayos y la seguridad social.'' -->
<!-- \textit{Revista de Econom\'ia, Banco Central del Uruguay, Vol. 16, No. 2}.  -->

<!-- \textbf{No arbitrado:}\\ -->

<!-- \item[2009]  Rodriguez, S., Alvarez, I., da Silva, N. ``Producto potencial y Brecha de Producto en Uruguay.''\\ \textit{Quantum, ISSN: 07977859, p. 4 - 21}.  -->

:::
